### ISSUE TITLE
No Data Loading

### ISSUE THREAD

**Issue by poltrian** [fhinder/MMM-RKI-Covid19#9]
Hello,

no data is loading. I installed the latest git version

**Comment by KristjanESPERANTO** [comment]
Did it work before you installed the latest git version? Show us your config of the module.

**Comment by fhinder** [comment]
Hello, 
the module is working on my side(latest version from git).

**Comment by SirFiChi** [comment]
Same issue here.
MagicMirror² is running in a fresh docker-container on a raspberry (with home assistant).
```

docker run -d --publish 82:8080 --restart always --volume ~/magic_mirror/config:/opt/magic_mirror/config --volume ~/magic_mirror/modules:/opt/magic_mirror/modules --name magic_mirror bastilimbach/docker-magicmirror
cd ~/magic_mirror/modules
git clone https://github.com/fhinder/MMM-RKI-Covid19.git
added following to the config.js
```

```
{
	module: "MMM-RKI-Covid19",
	position: "top_right",
	header: "RKI-Data",
	config:{
		reloadInterval: 60*60*1000,
		showUpdateTimestampInHeader: false,
		tableClass: "small",
		counties: [		
			'SK Köln',
			'SK Berlin Mitte',
			'SK München' 
		],
		states: [
			'Nordrhein-Westfalen',
			'Berlin',
			'Baden-Würtemberg'
		]
	}
},
```
Same issue for MMM-Fuel, MMM-COVID19 and MMM-Covid19-Vaccination:
![MM-Lade_Covid](https://user-images.githubusercontent.com/12483570/128641315-5b8f7a67-2bb4-4165-adb3-ca5f585ad71c.png)

So I think the docker container isn't able to reach the infos. (But the newsticker and holiday calender loaded there data...)

**Comment by poltrian** [comment]
Yes but my docker installation is not freshm for month it works, after a Docker Container update i run in an error. So i updated to the lastest version MM-covid19 runs again but no data loading. Same with "Impfdaten"

**Comment by poltrian** [comment]
No solution possible?

**Comment by KristjanESPERANTO** [comment]
Your config is working on my installation, but without docker.

Please try the new version of the module and do `npm install` in the module folder.

**Comment by poltrian** [comment]
Same, loading...

**Comment by KristjanESPERANTO** [comment]
Since I don't normally work with Docker, I unfortunately cannot reproduce the error. Would it be very time-consuming if you try to set up a new container in which you reinstall everything from scratch?

**Comment by poltrian** [comment]
Please give some days

**Comment by m00nSec** [comment]
Hey Folks,
I had the same issue within my docker container. I cloned the repository and executed `npm install` within the module folder. But all i got was "loading...". I could fix it by restarting the docker container. I had this issue with many other modules, so I always restart the container when I install a new module.
Please find attached my docker-compose config as well as my module config:

**docker-compose.yml**
```
version: '3.4

services:
  magicmirror:
    container_name: magicmirror
    image: karsten13/magicmirror:latest
    restart: unless-stopped
    volumes:
      - .config:/opt/magic_mirror/config
      - .modules:/opt/magic_mirror/modules
      - .css:/opt/magic_mirror/css
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.magicmirror.entrypoints=http"
      - "traefik.http.routers.magicmirror.rule=Host(`magicmirror.my.tld`)"
    networks:
      - traefik
    command: 
      - npm
      - run
      - server

networks:
  traefik:
    external: true
```
**config.js (module-config)**
```
{
	module: "MMM-RKI-Covid19",
	position: "top_right",
	header: "RKI-Data",
	config:{
		reloadInterval: 60*60*1000,
		showUpdateTimestampInHeader: false,
		showUpdateTimestampInFooter: false,
		tableClass: "small",
		counties: [		
			'SK Köln',
		],
		states: [
			'Niedersachsen',
		]
	}
}
```

Regards,
Moon
